# CloakGate 一级订阅模板
# __TOKEN__ 占位符会被替换为真实 token

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

proxy-providers:
  main:
    type: http
    url: '__API_DOMAIN__/provider?token=__TOKEN__'
    path: ./providers/main.yaml
    interval: 600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300

proxy-groups:
  - name: DMIT
    type: select
    use:
      - main
    proxies:
      - Auto

  - name: Auto
    type: url-test
    use:
      - main
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 50
rule-providers:
  YouTube:
    type: http
    behavior: classical
    url: 'https://api-gz.hosbbq.com/nus74f89st1/Y.yml'
    interval: 86400
    path: ./ruleset/YouTube.yml
  SteamCN:
    type: http
    behavior: classical
    url: 'https://api-gz.hosbbq.com/nus74f89st1/SC.yml'
    interval: 86400
    path: ./ruleset/SteamCN.yml
  Bahamut:
    type: http
    behavior: classical
    url: 'https://api-gz.hosbbq.com/nus74f89st1/Ba.yml'
    interval: 86400
    path: ./ruleset/Bahamut.yml
  DMM:
    type: http
    behavior: classical
    url: 'https://api-gz.hosbbq.com/nus74f89st1/DM.yml'
    interval: 86400
    path: ./ruleset/DMM.yml
  ChinaMax:
    type: http
    behavior: classical
    url: 'https://api-gz.hosbbq.com/nus74f89st1/C.yml'
    interval: 86400
    path: ./ruleset/ChinaMax.yml

rules:
  - DOMAIN,ic.adobe.io,REJECT
  - DOMAIN,dyzt55url8.adobe.io,REJECT
  - DOMAIN,gw8gfjbs05.adobe.io,REJECT
  - DOMAIN,0mo5a70cqa.adobe.io,REJECT
  - DOMAIN,ij0gdyrfka.adobe.io,REJECT
  - DOMAIN,dxyeyf6ecy.adobe.io,REJECT
  - DOMAIN,1hzopx6nz7.adobe.io,REJECT
  - DOMAIN,ph0f2h2csf.adobe.io,REJECT
  - DOMAIN,23ynjitwt5.adobe.io,REJECT
  - DOMAIN,crs.cr.adobe.com,REJECT
  - DOMAIN,www.photoshop.com,REJECT
  - DOMAIN,cc-cdn.adobe.com,REJECT
  - DOMAIN,photos.adobe.io,REJECT
  - DOMAIN,cc-api-data.adobe.io,REJECT
  - DOMAIN,lcs-cops.adobe.io,REJECT
  - DOMAIN,cai-splunk-proxy.adobe.io,REJECT
  - DOMAIN-KEYWORD,sjtu.edu.cn,DIRECT
  - DOMAIN-KEYWORD,linkedin,DMIT
  - DOMAIN-SUFFIX,okex.com,DMIT
  - DOMAIN-SUFFIX,oklink.com,DMIT
  - DOMAIN-SUFFIX,okx.com,DMIT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Bahamut,DMIT
  - RULE-SET,DMM,DMIT
  - RULE-SET,ChinaMax,DIRECT
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,DMIT